# Static configuration
entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
  format: json

accessLog:
  format: json
  filePath: /var/log/traefik/access.log

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: nextgen_local_nw
  file:
    directory: /etc/traefik/dynamic
    watch: true
